# Generated by Django 4.2.16 on 2024-11-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=100)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('maxRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxRate2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('user_count', models.IntegerField()),
                ('avg_satisfaction', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.product')),
            ],
            options={
                'db_table': 'user_statistics',
            },
        ),
    ]
