# Generated by Django 4.2.16 on 2024-11-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=100)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('maxRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxRate2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20)),
                ('income_level', models.CharField(max_length=20)),
                ('asset_level', models.CharField(max_length=20)),
                ('recommended_interest_rate', models.FloatField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('user_count', models.IntegerField()),
                ('avg_satisfaction', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.IntegerField()),
                ('asset_range', models.CharField(max_length=50)),
                ('income_range', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('preferred_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
    ]
