# Generated by Django 4.2.16 on 2024-11-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bankname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='joinway',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='maxRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='maxRate2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='products',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='special',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('bankname', 'products')},
        ),
    ]
